### PR TITLE
Check for JNI exception after each call. Fixes #41

### LINKED ISSUE #41: Check for JNI exception after each call
Some JNI functions are called, the exception result is not checked which causes a native crash on the next JNI call.

### PR DESCRIPTION
**Pull request by bluemarvin**

### CODE REVIEW

File: src/ClassLoaderAndroid.cpp [hunk 1]
```diff
@@ -61,6 +63,7 @@ jclass
 ClassLoaderAndroid::FindClass(const std::string& aClassName) const {
   jstring name = m.env->NewStringUTF(aClassName.c_str());
   jclass result = (jclass)(m.env->CallObjectMethod(m.classLoader, m.findClass, name));
+  VRB_CHECK_JNI_EXCEPTION(m.env);
   m.env->DeleteLocalRef(name);
   if (m.env->ExceptionCheck() == JNI_TRUE) {
```
Comment (MortimerGoro) [inline src/ClassLoaderAndroid.cpp]: This can be removed
